dist: trusty
language: python

sudo: false

python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - travis_retry pip install tox
    - travis_retry pip install tox-travis

script:
    - tox

after_success:
    - pip install coveralls
    - coveralls
