version: '2.1'
orbs:
  deploy-tools: zengrc/deploytools@1.0.0
workflows:
  build-and-deploy-main:
    jobs:
      - deploy-tools/build-and-push-image:
          filters:
            branches:
              only:
                - main
          name: Build
          repo_name: example
      - deploy-tools/deploy:
          cluster: development-1
          health_endpoint: 'https://example.dev.zengrc.io/service/ready'
          name: Deploy development-1
          namespace: example-dev
          repo_name: example
          requires:
            - Build